config/routes.rb
GrantApp::Application.routes.draw do
root to: 'static#index'
  
  get 'remove_attachment/' => 'grant_applications#delete_attachment'
  resources :grant_applications do
     member do
      patch 'select_grant_program_update'
      get 'select_grant_program', as: 'program'
      patch 'add_grant_details_update'
      get 'add_grant_details', as: 'details'
    end
  end
  
  get 'profile', to: 'users#profile', as: 'profile'

  post 'users/new' => 'users#create'
  
  resources :organizations do
    member do
      patch 'verify_eligibility_update'
      get 'verify_eligibility', as: 'verification'
    end
  end
  resources :users

  resource :subscriptions

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :grant_applications
    resources :users
    resources :organizations
    resources :programs
  end

  

end

app/models/grant_application.rb
class GrantApplication < ActiveRecord::Base  
	
  has_and_belongs_to_many :programs
	belongs_to :user
  belongs_to :organization
  mount_uploader :attachment, AttachmentUploader
  accepts_nested_attributes_for :programs
  attr_accessor :custom_grant_type

  def remove_attachment
  	path = "#{Rails.root}/public" + attachment_url
    #http://stackoverflow.com/questions/13352570/delete-folder-after-send-file-in-rails
  	FileUtils.remove_file(path)
    #https://github.com/carrierwaveuploader/carrierwave/issues/401
   	update_attributes(:remove_attachment => true) unless File.exists?(path)
  end

  def self_destruct
    self.destroy
  end

  def change_status(status)
  	change_attributes(status: status)
  end

end

app/controllers/admin/grant_applications_controller.rb
class Admin::GrantApplicationsController < Admin::AdminController
  before_filter :is_admin?, :non_admin_redirect

  def index
    @grant_applications = GrantApplication.all
  end

  def show
  	@grant_application = GrantApplication.find(params[:id])	
  end

  def edit
  	@grant_application = GrantApplication.find(params[:id])	
  end

  def update 
  	@grant_application = GrantApplication.find(params[:id])

  	if @grant_application.update_attributes(grant_application_params)
  		redirect_to admin_grant_applications_path
  	else 
  		render :edit
  	end
  end

  def destroy
    @grant_application = GrantApplication.find(params[:id])
    @grant_application.destroy
    redirect_to admin_grant_applications_path 
  end

  protected

  def grant_application_params
  	params.require(:grant_application).permit(:comments, :status, :attachment, :rating)
  end

end

app/controllers/grant_applications_controller.rb
require 'pry'

class GrantApplicationsController < ApplicationController
  before_filter :current_user, :if_not_user_redirect

  def index
    @grant_applications = GrantApplication.all
  end

  def show 
    @grant_application = GrantApplication.find(params[:id])
  end

  def new
    @user = User.find(session[:user_id])
   
    @grant_application = @user.grant_applications.new
  end

  def create
    @user = User.find(session[:user_id])
    @grant_application = @user.grant_applications.new(grant_application_params)
    @admins = User.where(is_admin: true)
    if @grant_application.save
      UserMailer.thankyou_email(@user).deliver
      AdminMailer.admin_notification_email(@admins, @grant_application).deliver
      redirect_to program_grant_application_path(@grant_application) 
    else
      render :new, notice: "Your application was not successfully submitted"
    end
  end

  def select_grant_program_update
    @grant_application = GrantApplication.find(params[:id])
    if @grant_application.update_attributes(grant_application_params)
      redirect_to details_grant_application_path(@grant_application)
    else
      render :select_grant_program
    end
  end

  def select_grant_program
    @grant_application = GrantApplication.find(params[:id])
  end

  def add_grant_details_update
    @grant_application = GrantApplication.find(params[:id])
    set_grant_type_to_custom
    if @grant_application.update_attributes(grant_application_params)
      redirect_to verification_organization_path(@grant_application.user.organization)
    else
      render :add_grant_details
    end
  end

  def add_grant_details
    @grant_application = GrantApplication.find(params[:id])
  end

  def add_supplemental_info
  end

  def delete_attachment
    current_user.grant_applications.find(params[:app_id]).remove_attachment
    redirect_to user_path(current_user)
  end

  protected

  def grant_application_params
    @grant_application_params ||= params.require(:grant_application).permit(:request_amount, :intended_use, :attachment, 
      :custom_grant_type, organizations_attributes: [ :business_number ], :grant_types => [], :program_ids => [])  
  end

  def set_grant_type_to_custom
     if grant_application_params[:custom_grant_type].present?
      grant_application_params[:grant_types] = grant_application_params[:custom_grant_type].split(" ")
    else
      grant_application_params[:grant_types]
    end
  end

end

app/helpers/grant_applications_helper.rb
module GrantApplicationsHelper
end

app/views/grant_applications/add_grant_details.html.erb
<h1>Add Grant Details</h1>

<%= form_for @grant_application, url: add_grant_details_update_grant_application_path(@grant_application) do |f| %>
  <div class="checkbox inline">
    <%= f.check_box :grant_types, { :multiple => true }, 'General Operations', nil %>
    <%= label_tag(:grant_types_general_operations, 'General Operations') %>
  </div><br>
  <div class="checkbox inline">
    <%= f.check_box :grant_types, { :multiple => true }, 'Capital Management', nil %>
    <%= label_tag(:grant_types_capital_management, 'Captial Management') %>
  </div><br>
   <div class="checkbox inline">
    <%= f.check_box :grant_types, { :multiple => true }, 'Program', nil %>
    <%= label_tag(:grant_types_program, 'Program') %>
  </div><br>
   <div class="checkbox inline">
    <%= f.check_box :grant_types, { :multiple => true }, 'Equipment', nil %>
    <%= label_tag(:grant_types_equipment, 'Equipment') %>
  </div><br>
   <div class="checkbox inline" id="other">
    <%= f.check_box :grant_types, { :multiple => true }, 'Other', nil %>
    <%= label_tag(:grant_types_other, 'Other') %>
  </div><br>
  <div id="create_other">
    <%= f.label :custom_grant_type, "Please Specify: " %>
    <%= f.text_field :custom_grant_type %>
  </div><br>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>
<div>
  <%= link_to "Back", program_grant_application_path(@grant_application) %>
</div>

app/views/grant_applications/edit.html.erb
<h1>GrantApplications#edit</h1>
<p>Find me in app/views/grant_applications/edit.html.erb</p>

app/views/grant_applications/new.html.erb
<%= link_to "Go back to profile", user_path(@user) %>

<h3>Your contact information | <%= link_to "edit", edit_user_path(@user) %></h3>
<p>Your name: <%= @user.first_name %> <%= @user.middle_initial%> <%= @user.last_name %></p>
<p>Organization: <%= @user.organization.name %></p>
<p>Email: <%= @user.email %></p>
<p>Phone Number: <%= @user.phone_number %></p>

<h3>Grant Details</h3>
<%= form_for @grant_application do |f| %>
  <div>
    <%= f.label "request_amount", "Grant Size" %><br>
    <%= f.text_field "request_amount" %>
  </div>
  <div>
    <%= f.label "intended_use", "Impact" %><br>
    <%= f.text_area "intended_use" %>
  </div>
  <div>
    <%= f.file_field :attachment %>
  </div>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/grant_applications/select_grant_program.html.erb
<h1>Select Grant Program</h1><br>

<p>Please indicate which grant program you are applying for</p><br />

<%= form_for @grant_application, url: select_grant_program_update_grant_application_path(@grant_application)  do |f| %>
  <div class="checkbox inline">
  <%= hidden_field_tag "grant_application[program_ids][]", nil %>
    <% Program.all.each do |program| %>
      <%= check_box_tag "grant_application[program_ids][]", program.id,
      @grant_application.program_ids.include?(program.id), id: dom_id(program)%>
      <%= label_tag dom_id(program), program.name %><br>
    <% end %>
  </div><br>
  <div>
    <%= f.submit "Save" %>
  </div>
<% end %>
<div>
  <%= link_to "Back", new_grant_application_path(@grant_application) %>
</div>

app/views/grant_applications/show.html.erb
<!-- 
This may be useful if we decide to create a place for the user to 
view past applications.
 -->

app/views/grant_applications/verify_eligibility.html.erb
<h1>Verify Eligibility</h1>

<%= form_for @grant_application, url: verify_eligibility_update_grant_application_path(@grant_application) do |f| %>
  <%= 'Is your organization a registered charity or other qualified done as defined under the income tax act?' %>
  <%= f.fields_for :organizations do |builder| %>
    <div>
    <%= builder.label :business_number, "Business Number" %>
    <%= builder.text_field :business_number %>
    </div>
  <% end %>
   <div>
    <%= f.submit "Save" %>
  </div>
<% end %>