config/routes.rb
GrantApp::Application.routes.draw do
root to: 'static#index'
  
  get 'remove_attachment/' => 'grant_applications#delete_attachment'
  resources :grant_applications do
     member do
      patch 'select_grant_program_update'
      get 'select_grant_program', as: 'program'
      patch 'add_grant_details_update'
      get 'add_grant_details', as: 'details'
    end
  end
  
  get 'profile', to: 'users#profile', as: 'profile'

  post 'users/new' => 'users#create'
  
  resources :organizations do
    member do
      patch 'verify_eligibility_update'
      get 'verify_eligibility', as: 'verification'
    end
  end
  resources :users

  resource :subscriptions

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :grant_applications
    resources :users
    resources :organizations
    resources :programs
  end

  

end

app/models/grant_application.rb
class GrantApplication < ActiveRecord::Base  
	
  has_and_belongs_to_many :programs
	belongs_to :user
  belongs_to :organization
  mount_uploader :attachment, AttachmentUploader
  accepts_nested_attributes_for :programs
  attr_accessor :custom_grant_type

  def remove_attachment
  	path = "#{Rails.root}/public" + attachment_url
    #http://stackoverflow.com/questions/13352570/delete-folder-after-send-file-in-rails
  	FileUtils.remove_file(path)
    #https://github.com/carrierwaveuploader/carrierwave/issues/401
   	update_attributes(:remove_attachment => true) unless File.exists?(path)
  end

  def self_destruct
    self.destroy
  end

  def change_status(status)
  	change_attributes(status: status)
  end

end

app/controllers/admin/grant_applications_controller.rb
class Admin::GrantApplicationsController < Admin::AdminController
  before_filter :is_admin?, :non_admin_redirect

  def index
    @grant_applications = GrantApplication.all
  end

  def show
  	@grant_application = GrantApplication.find(params[:id])	
  end

  def edit
  	@grant_application = GrantApplication.find(params[:id])	
  end

  def update 
  	@grant_application = GrantApplication.find(params[:id])

  	if @grant_application.update_attributes(grant_application_params)
  		redirect_to admin_grant_applications_path
  	else 
  		render :edit
  	end
  end

  def destroy
    @grant_application = GrantApplication.find(params[:id])
    @grant_application.destroy
    redirect_to admin_grant_applications_path 
  end

  protected

  def grant_application_params
  	params.require(:grant_application).permit(:comments, :status, :attachment, :rating)
  end

end

app/controllers/grant_applications_controller.rb
require 'pry'

class GrantApplicationsController < ApplicationController
  before_filter :current_user, :if_not_user_redirect

  def index
    @grant_applications = GrantApplication.all
  end

  def show 
    @grant_application = GrantApplication.find(params[:id])
  end

  def new
    @user = User.find(session[:user_id])
   
    @grant_application = @user.grant_applications.new
  end

  def create
    @user = User.find(session[:user_id])
    @grant_application = @user.grant_applications.new(grant_application_params)
    @admins = User.where(is_admin: true)
    if @grant_application.save
      UserMailer.thankyou_email(@user).deliver
      AdminMailer.admin_notification_email(@admins, @grant_application).deliver
      redirect_to program_grant_application_path(@grant_application) 
    else
      render :new, notice: "Your application was not successfully submitted"
    end
  end

  def select_grant_program_update
    @grant_application = GrantApplication.find(params[:id])
    if @grant_application.update_attributes(grant_application_params)
      redirect_to details_grant_application_path(@grant_application)
    else
      render :select_grant_program
    end
  end

  def select_grant_program
    @grant_application = GrantApplication.find(params[:id])
  end

  def add_grant_details_update
    @grant_application = GrantApplication.find(params[:id])
    set_grant_type_to_custom
    if @grant_application.update_attributes(grant_application_params)
      redirect_to verification_organization_path(@grant_application.user.organization)
    else
      render :add_grant_details
    end
  end

  def add_grant_details
    @grant_application = GrantApplication.find(params[:id])
  end

  def add_supplemental_info
  end

  def delete_attachment
    current_user.grant_applications.find(params[:app_id]).remove_attachment
    redirect_to user_path(current_user)
  end

  protected

  def grant_application_params
    @grant_application_params ||= params.require(:grant_application).permit(:request_amount, :intended_use, :attachment, 
      :custom_grant_type, organizations_attributes: [ :business_number ], :grant_types => [], :program_ids => [])  
  end

  def set_grant_type_to_custom
     if grant_application_params[:custom_grant_type].present?
      grant_application_params[:grant_types] = grant_application_params[:custom_grant_type].split(" ")
    else
      grant_application_params[:grant_types]
    end
  end

end

app/helpers/grant_applications_helper.rb
module GrantApplicationsHelper
end

app/views/admin/grant_applications/edit.html.erb
<h3>Welcome</h3>

<strong><%= @grant_application.user.first_name%> 
<%= @grant_application.user.last_name%><strong> from 
<%= @grant_application.user.organization.name %>
<%= link_to "User Information", admin_user_path(@grant_application.user) %> | 
<%= link_to "Delete Request", admin_grant_application_path(@grant_application), method: :delete, confirm: "Are You Sure?" %> <br/><br/>

Attachment
<%= button_to @grant_application.attachment_url, {class: "btn btn-small", method: :get} do %>
  File <i class="icon-paperclip"></i>
<% end %>

<%= form_for @grant_application, url: admin_grant_application_path(@grant_application) do |f| %>
<div>
  <%= f.label "Request Amount: #{@grant_application.request_amount}"  %><br/>
</div>
<div>
  <%= f.label "Intended Use: #{@grant_application.intended_use}" %><br/>
</div>
<div>
  <%= f.label "Rating" %><br/>
  <%= f.select(:rating, (1..10).to_a) %>
</div>
<div>
	<%= f.label "Reviewer Comments:" %><br/>
  <%= f.text_area :comments %>
</div>
<div>
	<%= f.label "Status" %>
	<%= f.select(:status, [["Review Pending","Review Pending"],["Follow Up","Follow Up"],["Denied","Denied"],["Approved","Approved"]]) %>
</div>
<div>
  <%= f.submit "Submit" %>
</div>
<% end %>

app/views/admin/grant_applications/index.html.erb
<h3>Welcome</h3>

<table class="table table-hover" id="datatable">
  <thead>
    <tr>
      <th>Date of Application</th>
      <th>ID</th>
      <th>Username</th>
      <th>Request Amount</th>
      <th>Status</th>
      <th>Rating</th>
      <th>Attachment</th>
    </tr>
  </thead>

  <tbody>
    <% @grant_applications.each do |g| %>
    
      <tr class="clickableRow applicationsTable" href="/admin/grant_applications/<%=g.id%>/edit">
        <td><%= g.created_at.strftime('%Y-%m-%d') %></td>
        <td><%= g.id %></td>

        <td>
          <% if g.user.username %>
            <%= g.user.username %>
          <% else %>
            <%= g.user.email %>
          <% end %>
        </td>

        <td><%= g.request_amount %></td>
        <td><%= g.status %></td>
        <td><%= g.rating %></td>
        <!-- File button -->
        <% if g.attachment_url != nil %>
          <td style="padding: 1px;"><%= button_to g.attachment_url, {class: "btn btn-small", method: :get} do %>
           File <i class="icon-paperclip"></i>
            <% end %>
          </td>
        <% else %>
          <td>No attachment</td>
        <% end %>
  
      </tr>
    <% end %>
  </tbody>
</table>

<script type="text/javascript">
  $('.applicationsTable').click(function() {
    // row was clicked
    console.log("sup world");
    window.location = $(this).attr("href");
  });

  $('.applicationsTable').hover(function() {
        $(this).css('cursor','hand');
    });
  $(".applicationsTable a").click( function(event) {
    event.stopPropagation();
  } );

</script>

app/views/admin/grant_applications/show.html.erb
<h1>this is admin show</h1>
<%= link_to "Back to admin home", admin_grant_applications_path %>

<%= @grant_application.request_amount %> <br/>
<%= @grant_application.intended_use %><br/>
<!-- comments should maybe be moved to it's own table.  -->
<%= @grant_application.comments %> <br/>
<%= @grant_application.status %> <br/>
<%= link_to @grant_application.attachment, @grant_application.attachment_url %><br/>


<%= link_to "Enter Review Zone", edit_admin_grant_application_path %>