config/routes.rb
GrantApp::Application.routes.draw do
root to: 'static#index'
  
  get 'remove_attachment/' => 'grant_applications#delete_attachment'
  resources :grant_applications do
     member do
      patch 'select_grant_program_update'
      get 'select_grant_program', as: 'program'
      patch 'add_grant_details_update'
      get 'add_grant_details', as: 'details'
    end
  end
  
  get 'profile', to: 'users#profile', as: 'profile'

  post 'users/new' => 'users#create'
  
  resources :organizations do
    member do
      patch 'verify_eligibility_update'
      get 'verify_eligibility', as: 'verification'
    end
  end
  resources :users

  resource :subscriptions

  resources :sessions, only: [:new, :create, :destroy]

  namespace :admin do
    resources :grant_applications
    resources :users
    resources :organizations
    resources :programs
  end

  

end

app/models/grant_application.rb
class GrantApplication < ActiveRecord::Base  
	
  has_and_belongs_to_many :programs
	belongs_to :user
  belongs_to :organization
  mount_uploader :attachment, AttachmentUploader
  accepts_nested_attributes_for :programs
  attr_accessor :custom_grant_type

  def remove_attachment
  	path = "#{Rails.root}/public" + attachment_url
    #http://stackoverflow.com/questions/13352570/delete-folder-after-send-file-in-rails
  	FileUtils.remove_file(path)
    #https://github.com/carrierwaveuploader/carrierwave/issues/401
   	update_attributes(:remove_attachment => true) unless File.exists?(path)
  end

  def self_destruct
    self.destroy
  end

  def change_status(status)
  	change_attributes(status: status)
  end

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  
  has_many :users
  has_many :grant_applications
  validates :name, presence: true
  validates_uniqueness_of :name

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :subscription

  validates :subscription_id, :amount, :charge_date, presence: true

end

app/models/plan.rb
class Plan < ActiveRecord::Base

  validates :name, :price, presence: true

  has_many :subcriptions

end

app/models/program.rb
class Program < ActiveRecord::Base
  has_and_belongs_to_many :grant_applications
  validates_presence_of :name
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base

  require 'pry'
  belongs_to :user
  belongs_to :plan 
  has_many :payments

  # before_save :set_next_payment_date
  after_save :gen_payment
  #Can't create payment before save because the payment needs a subscription id
  #which it won't have unless the subscription is saved.

  before_validation :set_signup_date
  validates :user, :plan, :signup_date, presence: true

  protected

#Responsibility of rebiller
  # def set_next_payment_date
  #   if self.next_payment_date.blank?
  #     self.next_payment_date = self.signup_date + 1.month
  #   else
  #     self.next_payment_date += 1.month
  #   end
  # end

  def gen_payment
    self.payments.create!(amount: self.plan.price, charge_date: Date.today)
  end

  def set_signup_date
    self.signup_date ||= Date.today
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  belongs_to :organization 
  has_many :grant_applications

  validates :first_name, :last_name, :phone_number, :email, presence: true
  validates :password, length: { in: 6..29}, on: :create

  before_save :generate_org

  attr_accessor :org_name

  protected

  def generate_org
    org = grab_organization
    unless org
      org = Organization.create!(name: self.org_name)
    end
    self.organization = org
  end

  def grab_organization
    Organization.where(name: self.org_name).first 
  end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  #Is a controller really only needed for the admin view?
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :current_user
  before_filter :if_not_user_redirect, only: [:show, :edit, :update] 

  def new
    @user = User.new
    @organization = Organization.new
    @organizations = Organization.all
  end

  def profile
    @user = User.find(session[:user_id])
    render :show
  end

  def create
  @user = User.new(user_params)
    if @user.save(user_params)
      session[:user_id] = @user.id
      redirect_to profile_path, notice: "Successfully registered."
    else 
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def show
    redirect_to admin_grant_applications_path if current_user.is_admin?
    @user = User.find(session[:user_id])
  end

  protected

  def user_params
    params.require(:user).permit(:org_name, :first_name, :last_name, :email, :phone_number, :password, :password_confirmation,
                          :organization_id, {:organizations => [ :name, :organization_id ]})
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/grants_helper.rb
module GrantsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
    <% if current_user %>
      Signed in as <%= current_user.email %> | <%= link_to "Home", user_path(current_user) %> | <%= link_to " Logout ", session_path("current"), method: :delete %> | 
    <% else %>
      <%= link_to "Login", new_session_path %> | <%= link_to "Sign Up", new_user_path %> 
    <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GrantApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <% if current_user %>
      <% if current_user.is_admin? %>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <!-- <a class="brand" href="<%= admin_grant_applications_path %> ">AdminHome</a> -->
          <div class="brand"><%= link_to "Admin Home", admin_grant_applications_path %></div>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Grant Applications", admin_grant_applications_path %></li>
              <li><%= link_to "Grantees", admin_users_path %></li>
              <li><%= link_to "Organizations", admin_organizations_path %></li>
              <li><%= link_to "Grant Programs",  admin_programs_path %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>
    <% end %>
  <% end %>

    <div class="container">
        <div class="row">
          <div class="span9">
            <%= bootstrap_flash %>
            <%= yield %>
          </div>
            <% if current_user %>
          </div>
    
    <% end %>
        </div><!--/row-->
    </div> <!-- /container -->



      <% unless request.env['PATH_INFO'] == root_path %>
        <div class="footer">
          <div class="container">
            <p><%= render 'layouts/footer' %> &copy; Company 2014</p>
          </div>
        </div> <!-- /container -->
      <% end %>
    

  </body>
</html>